package MAHLI;

import java.awt.Image;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class MAHLIDisplayCharts extends javax.swing.JApplet {
	private static final long serialVersionUID = 1L;

	PieChart pieChart = new PieChart();
	BarChart barChart = new BarChart();
	ChartModel chartModel = new ChartModel();

	/** Creates new form MAHLIDisplayCharts */
	public MAHLIDisplayCharts() {
		initComponents();
		pieChart.setModel(chartModel);
		barChart.setModel(chartModel);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		jPanel = new JPanel();
		jLabel = new JLabel();
		jbtPieChart = new JButton();
		jbtBarChart = new JButton();
		imagePath = chartModel.getImagePath();
		imageIcon = new ImageIcon(imagePath);
		
		jbtPieChart.setText("View Pie Chart");
		jbtPieChart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtPieChartActionPerformed(evt);
			}
		});

		jPanel.add(jbtPieChart);

		jbtBarChart.setText("View Bar Chart");
		jbtBarChart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtBarChartActionPerformed(evt);
			}
		});

		jPanel.add(jbtBarChart);

		getContentPane().add(jPanel, java.awt.BorderLayout.SOUTH);
		
		jLabel.setSize(100, 100);
		jLabel.setIcon(imageIcon);
		getContentPane().add(jLabel, java.awt.BorderLayout.CENTER);

	}//GEN-END:initComponents

	private void jbtBarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBarChartActionPerformed
		JFrame barChartFrame = new JFrame("View Bar Chart");
		barChartFrame.getContentPane().add(barChart);
		barChartFrame.setSize(400, 400);
		barChartFrame.setVisible(true);
	}//GEN-LAST:event_jbtBarChartActionPerformed

	private void jbtPieChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPieChartActionPerformed
		JFrame pieChartFrame = new JFrame("View Pie Chart");
		pieChartFrame.getContentPane().add(pieChart);
		pieChartFrame.setSize(400, 400);
		pieChartFrame.setVisible(true);
	}//GEN-LAST:event_jbtPieChartActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JPanel jPanel;
	private JLabel jLabel;
	private JButton jbtBarChart;
	private JButton jbtPieChart;
	private ImageIcon imageIcon;
	private String imagePath;
	// End of variables declaration//GEN-END:variables

	public void displayApplet(){
		MAHLIDisplayCharts applet = new MAHLIDisplayCharts();
		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(3);
		frame.setTitle("MAHLI Data Analysis");
		frame.getContentPane().add(applet, java.awt.BorderLayout.CENTER);
		frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
		applet.init();
		applet.start();
		frame.setSize(400,320);
		//frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLocationRelativeTo(null); // Center the frame
		frame.setVisible(true);
	}
}
