package MAHLI;

import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class MAHLIDisplayCharts extends javax.swing.JApplet {
	private static final long serialVersionUID = 1L;

	PieChart pieChart1 = new PieChart();
	BarChart barChart1 = new BarChart();
	ChartModel chartModel1 = new ChartModel();

	/** Creates new form Exercise36_5 */
	public MAHLIDisplayCharts() {
		initComponents();
		pieChart1.setModel(chartModel1);
		barChart1.setModel(chartModel1);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		jPanel = new javax.swing.JPanel();
		jLabel = new javax.swing.JLabel();
		jbtPieChart = new javax.swing.JButton();
		jbtBarChart = new javax.swing.JButton();

		jbtPieChart.setText("View Pie Chart");
		jbtPieChart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtPieChartActionPerformed(evt);
			}
		});

		jPanel.add(jbtPieChart);

		jbtBarChart.setText("View Bar Chart");
		jbtBarChart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtBarChartActionPerformed(evt);
			}
		});

		jPanel.add(jbtBarChart);

		getContentPane().add(jPanel, java.awt.BorderLayout.SOUTH);
		
		jLabel.setIcon(imageIcon);
		getContentPane().add(jLabel, java.awt.BorderLayout.CENTER);

	}//GEN-END:initComponents

	private void jbtBarChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBarChartActionPerformed
		JFrame barChartFrame = new JFrame("View Bar Chart");
		barChartFrame.getContentPane().add(barChart1);
		barChartFrame.setSize(400, 400);
		barChartFrame.setVisible(true);
	}//GEN-LAST:event_jbtBarChartActionPerformed

	private void jbtPieChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPieChartActionPerformed
		JFrame pieChartFrame = new JFrame("View Pie Chart");
		pieChartFrame.getContentPane().add(pieChart1);
		pieChartFrame.setSize(400, 400);
		pieChartFrame.setVisible(true);
	}//GEN-LAST:event_jbtPieChartActionPerformed


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel jPanel;
	private javax.swing.JLabel jLabel;
	private javax.swing.JButton jbtBarChart;
	private javax.swing.JButton jbtPieChart;
	private ImageIcon imageIcon = new ImageIcon("C:\\Users\\hensan\\Documents\\workspace2\\MAHLI\\src\\MAHLI\\resources\\images\\1.jpg");
	private Image image= imageIcon.getImage();
	// End of variables declaration//GEN-END:variables

	public void displayApplet(){
		MAHLIDisplayCharts applet = new MAHLIDisplayCharts();
		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(3);
		frame.setTitle("MAHLI Display Charts");
		frame.getContentPane().add(applet, java.awt.BorderLayout.CENTER);
		applet.init();
		applet.start();
		frame.setSize(400,320);
		//frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setLocationRelativeTo(null); // Center the frame
		frame.setVisible(true);
	}
}
