package MAHLI;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;

import javax.swing.JApplet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import json.ReadFromJSON;

public class MAHLIDisplayCharts extends JApplet {
	private static final long serialVersionUID = 1L;
	
	PieChart pieChart = new PieChart();
	BarChart barChart = new BarChart();
	ChartModel chartModel = new ChartModel();
	ReadFromJSON readJSON = new ReadFromJSON();
	File dataFile = null;
	
	
	/** Creates new form MAHLIDisplayCharts 
	 * @throws IOException */
	public MAHLIDisplayCharts() throws IOException {
		initComponents();
		pieChart.setModel(chartModel);
		barChart.setModel(chartModel);
	}
	
	/** This method is called from within the constructor to
	* initialize the form.
	* WARNING: Do NOT modify this code. The content of this method is
	* always regenerated by the Form Editor.
	 * @throws IOException 
	*/
	private void initComponents() throws IOException {
		jPanel = new JPanel();
		jbtPieChart = new JButton();
		jbtBarChart = new JButton();
	
		jbtPieChart.setText("View Pie Chart");
	  	jbtPieChart.addActionListener(new ActionListener() {
	  		public void actionPerformed(ActionEvent evt) {
	  			jbtPieChartActionPerformed(evt);
	  		}
		});
		
		jPanel.add(jbtPieChart);
		
		jbtBarChart.setText("View Bar Chart");
		jbtBarChart.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jbtBarChartActionPerformed(evt);
			}
		});
		  
		 jPanel.add(jbtBarChart);
		 getContentPane().add(jPanel, BorderLayout.SOUTH);
		 
		 final ZoomLabel label = new ZoomLabel();
         try{
             Image img = javax.imageio.ImageIO.read(new File("src/MAHLI/resources/images/" + 2 + ".jpg"));
             label.setImage(img);
         }catch(Exception e) {
             System.err.println("Couldn't load image for demonstration");
             e.printStackTrace();
             System.exit(0);
         }
         
		 getContentPane().add(label, BorderLayout.NORTH);
	}
	
	private void jbtBarChartActionPerformed(java.awt.event.ActionEvent evt) {
	  JFrame barChartFrame = new JFrame("View Bar Chart");
	  barChartFrame.getContentPane().add(barChart);
	  barChartFrame.setSize(500, 500);
	  barChartFrame.setVisible(true);
	}
	
	private void jbtPieChartActionPerformed(ActionEvent evt) {
	  JFrame pieChartFrame = new JFrame("View Pie Chart");
	  pieChartFrame.getContentPane().add(pieChart);
	  pieChartFrame.setSize(500, 500);
	  pieChartFrame.setVisible(true);
	}
	
	
	// Variables declaration - do not modify
	private JPanel jPanel;
	private JButton jbtBarChart;
	private JButton jbtPieChart;
	private File file;
	private Long[] data;
	private String[] dataName;
	
	public void setData(Long[] data){
		this.data = data;
	}
	
	public Long[] getData(){
		return data;
	}
	
	public void setDataName(String[] dataName){
		this.dataName = dataName;
	}
	
	public String[] getDataName() {
		return dataName;
	}
	
	public File getFile(){
		return file;
	}
	
	public void setFile(String file){
		this.file = new File(file);
	}
}
